-- activity: 활동(액티비티) 테이블
create table if not exists public.activity (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  generation_id bigint null,
  title text null,
  description text null,
  category text null,
  date date null,
  image_url text null,
  update_at timestamp with time zone null default now(),
  constraint activity_pkey primary key (id),
  constraint activity_generation_id_fkey foreign key (generation_id) references public.generations (id)
) tablespace pg_default;

-- activity_media: 활동 미디어(이미지/영상) 테이블
create table if not exists public.activity_media (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  activity_id bigint null,
  media_type text null default 'image'::text,
  media_url text null,
  display_order bigint null,
  constraint activity_media_pkey primary key (id),
  constraint activity_media_activity_id_fkey foreign key (activity_id) references public.activity (id) on delete cascade
) tablespace pg_default;

-- RLS 정책 (선택: 관리자만 접근 시 사용)
-- alter table public.activity enable row level security;
-- alter table public.activity_media enable row level security;
